[mem_by_pass_scale]
width=400
height=200

[picture_quality]
pqmode=1

[frame_swtich]
; 使能开关 0：不启用切换 1：RGB888到RGB565动态切换
frame_switch_enable=3
; 动态切换，根据实际帧率切换(frame_Enable = 2) 12：帧率低于12切换成565， 20：帧率大于20切换成888
frame_avg_fre_0=42
frame_avg_fre_1=18
frame_time=3

