PACKAGE_NAME="ms912x"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="ms912x"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KVER=${kernelver} KSRC=${kernel_source_dir}"
CLEAN="make KVER=${kernelver} KSRC=${kernel_source_dir} clean"
